### PR TITLE
fixed the terrible

### LINKED ISSUE #56: the x is nqr

### PR DESCRIPTION
**Pull request by meelijane**
Fixes #56

### CODE REVIEW

File: src/menu/flower.cljs [hunk 1]
```diff
@@ -20,8 +20,8 @@
  (let [transition-length (/ transition-length 2)]
   (h/div
    :css (j/cell= {:position "fixed"
-                  :left (u/n->px outer-radius)
-                  :bottom (u/n->px outer-radius)
+                  :left (u/n->px (.round js/Math outer-radius))
```
Comment (thedavidmeister) [inline src/menu/flower.cljs]: why not define a new function like `(def n->px-rounded (comp n->px Math/round))`

File: src/menu/flower.cljs [hunk 2]
```diff
@@ -60,12 +60,13 @@
                                     2))
          height (j/cell= (/ radius 12))
          ; rotated-offset (j/cell= (* 2 width))
-         left (j/cell= (+ radius (- (/ width 2))))
-         top (j/cell= (+ radius (- (/ height 2))))
+         left (j/cell= (.round js/Math (+ radius (- (/ width 2)))))
```
Comment (thedavidmeister) [inline src/menu/flower.cljs]: you can just do `Math/round` btw, and this works in both java and javascript (because JS copied the java Math object)

**Comment by thedavidmeister** [comment]
this only needed a tiny bit of rounding in the end.

there were two problems:
- need some rounding on the initial height/width for each bar
- the offset calculations were totally wrong

before:

screen shot 2017-12-19 at 2 10 26 pm

after:

screen shot 2017-12-19 at 2 10 56 pm
